<?php
/**
 * Server render for loop-builder/query.
 *
 * The query block is a thin wrapper: WordPress has already rendered the inner
 * blocks (the template + no-results) into $content, each of which received this
 * block's query/layout context. We only apply the block supports wrapper here.
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Rendered inner blocks.
 * @var WP_Block $block      Block instance.
 *
 * @package LoopBuilder
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( empty( trim( $content ) ) ) {
	return;
}

$tag_name        = isset( $attributes['tagName'] ) ? tag_escape( $attributes['tagName'] ) : 'div';
$wrapper_classes = 'wp-block-loop-builder';
$wrapper_attrs   = get_block_wrapper_attributes( array( 'class' => $wrapper_classes ) );

printf(
	'<%1$s %2$s>%3$s</%1$s>',
	$tag_name, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- tag_escape'd above.
	$wrapper_attrs, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by core.
	$content // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- rendered inner blocks.
);
